development:
  adapter: sqlite3
  database: db/development.sqlite3

  test:
    adapter: sqlite3
    database: db/test.sqlite3

  production:
    adapter: postgresql
    database: kanban
    username: nikolett
    password: fdkuygkufdjhgk
    host: ENV["DATABASE_URL"]